packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  '@google/genai': true
  protobufjs: true
patchedDependencies:
  '@sveltejs/adapter-vercel': patches/@sveltejs__adapter-vercel.patch
