packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  '@google/genai': true
  protobufjs: true
patchedDependencies:
  '@sveltejs/adapter-vercel@7.0.0': patches/@sveltejs__adapter-vercel.patch
  '@sveltejs/kit@3.0.0': patches/@sveltejs__kit@3.0.0.patch
