import { defineEnvVars } from '@sveltejs/kit/env';

export const variables = defineEnvVars({
	DATABASE_URL: { schema: (input) => input ?? '' },
	PLAYWRIGHT_TEST: { schema: (input) => input ?? '' },
	MICROSOFT_TENANT_ID: { schema: (input) => input ?? '' },
	MICROSOFT_CLIENT_ID: { schema: (input) => input ?? '' },
	MICROSOFT_CLIENT_SECRET: { schema: (input) => input ?? '' },
	GEMINI_API_KEY: { schema: (input) => input ?? '' },
	CRON_SECRET: { schema: (input) => input ?? '' },
	BETTER_AUTH_URL: { schema: (input) => input ?? '' },
	BETTER_AUTH_SECRET: { schema: (input) => input ?? '' },
	GOOGLE_CLIENT_ID: { schema: (input) => input ?? '' },
	GOOGLE_CLIENT_SECRET: { schema: (input) => input ?? '' },
	PUBLIC_BASE_URL: { schema: (input) => input ?? '' },
	ABLY_API_KEY: { schema: (input) => input ?? '' },
	VERCEL: { schema: (input) => input ?? '' },
	CF_PAGES: { schema: (input) => input ?? '' },
	ENABLE_REALTIME_POLLING: { schema: (input) => input ?? '' },
	FORCE_ABLY: { schema: (input) => input ?? '' },
	SYNC_WEBHOOK_URL: { schema: (input) => input ?? '' },
	SYNC_MAX_DURATION_SECONDS: { schema: (input) => input ?? '' },
	MAX_DURATION: { schema: (input) => input ?? '' },
	BERLIN_DE_MH_API_URL: { schema: (input) => input ?? '' },
	ORG_NAME: { schema: (input) => input ?? '' },
	ORG_WWW: { schema: (input) => input ?? '' },
	BREVO_API_KEY: { schema: (input) => input ?? '' },
	EVENTBRITE_CLIENT_ID: { schema: (input) => input ?? '' },
	EVENTBRITE_CLIENT_SECRET: { schema: (input) => input ?? '' },
	MEETUP_CLIENT_ID: { schema: (input) => input ?? '' },
	MEETUP_CLIENT_SECRET: { schema: (input) => input ?? '' },
	NEBENAN_DE_API_URL: { schema: (input) => input ?? '' },
	WP_EVENTS_CALENDAR_BASE_URL: { schema: (input) => input ?? '' },
	WP_EVENTS_CALENDAR_USERNAME: { schema: (input) => input ?? '' },
	WP_EVENTS_CALENDAR_APP_PASSWORD: { schema: (input) => input ?? '' },
	REDIS_URL: { schema: (input) => input ?? '' },
	BLOB_READ_WRITE_TOKEN: { schema: (input) => input ?? '' }
});
